language: ruby
rvm:
 - 2.4.4
 - 2.5.1
 - ruby-head

allow_failures:
  - rvm: ruby-head
  
before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"
  - "travis_retry gem update --system"
  - "travis_retry gem install bundler"

script: bundle exec rake
